// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouswjhtszonatjizdlqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91c3dqaHRzem9uYXRqaXpkbHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjY4OTksImV4cCI6MjA1NzgwMjg5OX0.F2fXOBkP612LiA4GV8OXgnOPADzSrRkxoW4OSN9UzG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);